"""SQLAlchemy declarative base and shared model mixins.

Every table inherits ``Base``. The naming convention is declared explicitly so
indexes and constraints get deterministic names, which keeps Alembic
autogeneration diffs stable and reviewable.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Final

from sqlalchemy import DateTime, ForeignKey, Index, Integer, MetaData, event, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, declared_attr, mapped_column
from sqlalchemy.schema import SchemaItem

NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all Wasla models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by the application."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Database-managed audit timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class RevisionedMixin:
    """A row whose every change bumps a counter, for optimistic concurrency.

    What an operator's `expected_revision` is compared with before a platform
    billing mutation (BILL-12): Admin A reads revision 4, Admin B changes the
    row to revision 5, and A's edit based on 4 is refused with 409 instead of
    silently overwriting B's. The comparison is made under a row lock, so the
    check and the write cannot interleave.

    Bumped by `_bump_revisions` below on every flush that changes the row,
    rather than by each service remembering to: a counter that one code path
    forgets to increment is a counter that says "unchanged" about a changed
    row. Bulk `UPDATE` statements bypass the ORM and must bump it themselves.
    """

    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")


@event.listens_for(Session, "before_flush")
def _bump_revisions(session: Session, flush_context: object, instances: object) -> None:
    """Advance `revision` on every revisioned row this flush changes."""
    for instance in session.dirty:
        if isinstance(instance, RevisionedMixin) and session.is_modified(
            instance, include_collections=False
        ):
            instance.revision = (instance.revision or 0) + 1


class SoftDeleteMixin:
    """Opt-in soft deletion. Applied deliberately, not to every table."""

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class TenantScopedMixin:
    """Tenant ownership for tenant-owned tables (ADR-001).

    Provides the ``tenant_id`` foreign key and its index. Isolation itself is
    enforced in repositories and services; this mixin only guarantees that the
    column and index exist wherever tenant data is stored.

    Careful: a model that declares ``__table_args__`` in its own class body
    *replaces* the value below instead of extending it, and so loses the tenant
    index without any error. Models that need extra table arguments must restate
    the index themselves. ``tests/unit/test_whatsapp_models.py`` asserts that
    every mapped table carrying a ``tenant_id`` column has its index, which is
    the guard against repeating that mistake.
    """

    # Declared directly rather than through ``declared_attr``. SQLAlchemy 2.0
    # copies a mixin's ``mapped_column`` - foreign key included - onto each
    # mapped subclass, and the direct form is what lets a type checker resolve
    # ``instance.tenant_id`` to a UUID instead of to the Mapped descriptor.
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )

    @declared_attr.directive
    @classmethod
    def __table_args__(cls) -> tuple[SchemaItem, ...]:
        # Typed as SchemaItem rather than Index because subclasses override this
        # with constraints alongside their indexes, and a narrower type here
        # makes every one of those overrides a type error.
        table_name = cls.__tablename__  # type: ignore[attr-defined]
        return (Index(f"ix_{table_name}_tenant_id", "tenant_id"),)
