"""Declarative models. Importing this package registers every table on `Base`."""

from app.db.base import Base

from .agent import Agent, AgentStatus, AgentTool
from .analytics import AnalyticsEvent, AnalyticsEventType, AnalyticsSource
from .audit import AuditAction, AuditActorKind, AuditLog
from .billing import (
    PERIOD_LIMITS,
    RESOURCE_LIMITS,
    SERVING_STATUSES,
    TERMINAL_SUBSCRIPTION_STATUSES,
    BillingInterval,
    LimitKey,
    Plan,
    Subscription,
    SubscriptionStatus,
)
from .campaign import (
    MAX_RECIPIENT_ATTEMPTS,
    TERMINAL_CAMPAIGN_STATUSES,
    Campaign,
    CampaignRecipient,
    CampaignStatus,
    OptOutSource,
    RecipientStatus,
)
from .conversation import (
    Contact,
    Conversation,
    ConversationMode,
    ConversationStatus,
    Message,
    MessageDirection,
    MessageKind,
    MessageStatus,
)
from .email import (
    TERMINAL_EMAIL_STATUSES,
    EmailStatus,
    EmailSuppression,
    OutboundEmail,
)
from .email_verification import (
    DEFAULT_MAX_VERIFICATION_ATTEMPTS,
    DEFAULT_VERIFICATION_TTL_SECONDS,
    EmailVerificationChallenge,
)
from .enums import (
    InvitationStatus,
    MembershipStatus,
    PlatformRole,
    TenantRole,
    TenantStatus,
)
from .follow_up import (
    MAX_ATTEMPTS,
    TERMINAL_FOLLOW_UP_STATUSES,
    FollowUp,
    FollowUpStatus,
)
from .invitation import TenantInvitation
from .invoice import (
    TERMINAL_INVOICE_STATUSES,
    Invoice,
    InvoiceStatus,
    Payment,
    PaymentStatus,
)
from .knowledge import (
    EMBEDDING_DIMENSIONS,
    Document,
    DocumentChunk,
    DocumentSource,
    DocumentStatus,
    KnowledgeBase,
)
from .lead import (
    AGENT_WRITABLE_FIELDS,
    ALLOWED_TRANSITIONS,
    MAX_SCORE,
    MIN_SCORE,
    TERMINAL_STATUSES,
    ActorKind,
    Lead,
    LeadActivity,
    LeadActivityKind,
    LeadNote,
    LeadSource,
    LeadStatus,
    clamp_score,
)
from .media import UNRESOLVED_MEDIA_STATUSES, MediaStatus, MessageMedia
from .membership import Membership
from .password_reset import PasswordResetToken
from .payment_event import PaymentEvent
from .sentiment import (
    PRIORITY_RANK,
    SENTIMENT_PRIORITY,
    SENTIMENT_SEVERITY,
    ConversationPriority,
    MessageSentiment,
    SentimentLabel,
    is_at_least,
    raised_priority,
)
from .tenant import Tenant
from .usage import (
    EVENT_UNITS,
    UsageEvent,
    UsageEventType,
    UsageUnit,
    unit_for,
)
from .user import User
from .whatsapp import (
    WhatsAppAccount,
    WhatsAppAccountStatus,
    WhatsAppEvent,
    WhatsAppEventKind,
    WhatsAppEventState,
)
from .whatsapp_template import (
    TemplateCategory,
    TemplateStatus,
    WhatsAppTemplate,
    count_placeholders,
)

__all__ = [
    "AGENT_WRITABLE_FIELDS",
    "ALLOWED_TRANSITIONS",
    "DEFAULT_MAX_VERIFICATION_ATTEMPTS",
    "DEFAULT_VERIFICATION_TTL_SECONDS",
    "EMBEDDING_DIMENSIONS",
    "EVENT_UNITS",
    "MAX_ATTEMPTS",
    "MAX_RECIPIENT_ATTEMPTS",
    "MAX_SCORE",
    "MIN_SCORE",
    "PERIOD_LIMITS",
    "PRIORITY_RANK",
    "RESOURCE_LIMITS",
    "SENTIMENT_PRIORITY",
    "SENTIMENT_SEVERITY",
    "SERVING_STATUSES",
    "TERMINAL_CAMPAIGN_STATUSES",
    "TERMINAL_EMAIL_STATUSES",
    "TERMINAL_FOLLOW_UP_STATUSES",
    "TERMINAL_INVOICE_STATUSES",
    "TERMINAL_STATUSES",
    "TERMINAL_SUBSCRIPTION_STATUSES",
    "UNRESOLVED_MEDIA_STATUSES",
    "ActorKind",
    "Agent",
    "AgentStatus",
    "AgentTool",
    "AnalyticsEvent",
    "AnalyticsEventType",
    "AnalyticsSource",
    "AuditAction",
    "AuditActorKind",
    "AuditLog",
    "Base",
    "BillingInterval",
    "Campaign",
    "CampaignRecipient",
    "CampaignStatus",
    "Contact",
    "Conversation",
    "ConversationMode",
    "ConversationPriority",
    "ConversationStatus",
    "Document",
    "DocumentChunk",
    "DocumentSource",
    "DocumentStatus",
    "EmailStatus",
    "EmailSuppression",
    "EmailVerificationChallenge",
    "FollowUp",
    "FollowUpStatus",
    "InvitationStatus",
    "Invoice",
    "InvoiceStatus",
    "KnowledgeBase",
    "Lead",
    "LeadActivity",
    "LeadActivityKind",
    "LeadNote",
    "LeadSource",
    "LeadStatus",
    "LimitKey",
    "MediaStatus",
    "Membership",
    "MembershipStatus",
    "Message",
    "MessageDirection",
    "MessageKind",
    "MessageMedia",
    "MessageSentiment",
    "MessageStatus",
    "OptOutSource",
    "OutboundEmail",
    "PasswordResetToken",
    "Payment",
    "PaymentEvent",
    "PaymentStatus",
    "Plan",
    "PlatformRole",
    "RecipientStatus",
    "SentimentLabel",
    "Subscription",
    "SubscriptionStatus",
    "TemplateCategory",
    "TemplateStatus",
    "Tenant",
    "TenantInvitation",
    "TenantRole",
    "TenantStatus",
    "UsageEvent",
    "UsageEventType",
    "UsageUnit",
    "User",
    "WhatsAppAccount",
    "WhatsAppAccountStatus",
    "WhatsAppEvent",
    "WhatsAppEventKind",
    "WhatsAppEventState",
    "WhatsAppTemplate",
    "clamp_score",
    "count_placeholders",
    "is_at_least",
    "raised_priority",
    "unit_for",
]
