"""let a caller say a send is the same send as before

Revision ID: 0055
Revises: 0054

A double-clicked send button, a retried mobile request or a proxy replay put
two copies of the same message on a customer's phone, because the outbound API
took nothing that could tell a repeat from a second message (MSG-15). Meta's
send endpoint offers no idempotency key either, so this has to be solved here.

**A key, not a content comparison.** Sending the same words twice is a thing
people legitimately do - "are you there?" twice is two messages - so suppressing
a duplicate body within a time window would silently swallow real intent. The
caller says which requests are the same request, and nothing else does.

Scoped to the workspace, mirroring `uq_payments_tenant_id_idempotency_key`
exactly: keys are generated by clients and two workspaces choosing the same
UUID must not collide. Nullable, because most sends do not carry one and NULLs
are distinct under a unique constraint, so any number of keyless messages
coexist.

The constraint is the guarantee, not the read beside it. Two simultaneous
submissions of one key both miss the read; one of them loses here, and losing
is what makes the second request return the first request's message instead of
asking Meta a second time.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0055"
down_revision = "0054"
branch_labels = None
depends_on = None

# Matches `MAX_IDEMPOTENCY_KEY_LENGTH` in app/db/models/invoice.py, which is
# where this length was first settled.
KEY_LENGTH = 100


def upgrade() -> None:
    op.add_column(
        "messages",
        sa.Column("idempotency_key", sa.String(length=KEY_LENGTH), nullable=True),
    )
    op.create_unique_constraint(
        "uq_messages_tenant_id_idempotency_key",
        "messages",
        ["tenant_id", "idempotency_key"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "uq_messages_tenant_id_idempotency_key",
        "messages",
        type_="unique",
    )
    op.drop_column("messages", "idempotency_key")
