"""The five Google endpoints, over HTTP, against a real database.

`test_google_profile.py` drives `GoogleAuthService` directly. That proves the
rules but says nothing about the layer above: whether the routes are mounted
where the matrix claims, whether the guards resolve, whether a refusal deep in
the service becomes the status code the API contract promises, and whether the
transaction the route opened is what ends up in PostgreSQL.

**Only Google's network is stubbed.** The verifier is the real one and does real
RS256 validation against a real key set, over tokens really signed by a real RSA
key - the same machinery `test_google_oidc.py` uses. The authorization URL is
built by the real client. The flow store, the service, the repositories, the
audit trail, the token issuer and the database are all real, and the state and
nonce are read back out of the store the way Google would carry them, rather
than invented by the test. What is replaced is exactly one method - the HTTPS
call to Google's token endpoint - because a test that needed real Google
credentials would be a test nobody can run.

This is the closest a suite can get to the browser flow without a Google client
id. It is **not** a substitute for one: no test here proves that Google accepts
this deployment's redirect URI, that the consent screen renders, or that a real
`sub` looks like what the model expects. See `docs/GOOGLE_OAUTH.md`.
"""

from __future__ import annotations

import base64
import json
from collections.abc import AsyncIterator, Iterator
from datetime import UTC, datetime, timedelta
from urllib.parse import parse_qs, urlsplit

import jwt
import pytest
import pytest_asyncio
from cryptography.hazmat.primitives.asymmetric import rsa
from fastapi import FastAPI, Request
from httpx import ASGITransport, AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies import get_entitlement_service
from app.api.v1 import google_oauth as google_routes
from app.core.config import Settings
from app.core.dependencies import SESSION_STATE_ATTRIBUTE, get_session
from app.core.security import create_access_token
from app.db.models.audit import AuditAction, AuditLog
from app.db.models.identity import FederatedIdentity, IdentityProvider
from app.db.models.user import User
from app.integrations.google.client import GoogleOAuthClient
from app.integrations.google.oidc import GoogleKeyRing
from app.main import create_app
from tests.conftest import AllowingEntitlements, FakeDependency

pytestmark = pytest.mark.integration

API = "/api/v1"

# Shaped like a real one, because `Settings` checks the suffix. It authenticates
# nothing: every token below is signed by the key generated here, and the
# verifier is told to trust that key and no other.
CLIENT_ID = "1234567890-testclient.apps.googleusercontent.com"
REDIRECT_URI = "https://app.wasla.test/auth/google/callback"
KID = "endpoint-test-key"
ISSUER = "https://accounts.google.com"

SUBJECT = "109876543210987654321"
GOOGLE_EMAIL = "google-person@example.com"
GOOGLE_NAME = "A Google Person"
GOOGLE_PICTURE = "https://lh3.googleusercontent.com/a/endpoint=s96-c"

_SIGNING_KEY = rsa.generate_private_key(public_exponent=65537, key_size=2048)


def _jwks() -> dict[str, object]:
    jwk = dict(jwt.algorithms.RSAAlgorithm.to_jwk(_SIGNING_KEY.public_key(), as_dict=True))
    jwk.update({"kid": KID, "use": "sig", "alg": "RS256"})
    return {"keys": [jwk]}


def _id_token(*, nonce: str, **overrides: object) -> str:
    """A genuinely signed Google ID token, which the real verifier will check."""
    now = datetime.now(UTC)
    payload: dict[str, object] = {
        "iss": ISSUER,
        "aud": CLIENT_ID,
        "sub": SUBJECT,
        "email": GOOGLE_EMAIL,
        "email_verified": True,
        "name": GOOGLE_NAME,
        "picture": GOOGLE_PICTURE,
        "nonce": nonce,
        "iat": int(now.timestamp()),
        "exp": int((now + timedelta(minutes=5)).timestamp()),
    }
    payload.update(overrides)
    return jwt.encode(payload, _SIGNING_KEY, algorithm="RS256", headers={"kid": KID})


class _FixedKeyRing(GoogleKeyRing):
    """Google's key document, served from memory instead of over the network."""

    async def _fetch(self) -> dict[str, object]:
        return _jwks()


class _Exchange:
    """What Google's token endpoint would have returned.

    A mutable holder rather than a constructor argument, because the token can
    only be minted once the nonce is known - and the nonce is generated by the
    real flow store during the `authorize` request.
    """

    def __init__(self) -> None:
        self.id_token: str | None = None
        self.error: Exception | None = None
        self.calls: list[dict[str, str]] = []


class _StubbedClient(GoogleOAuthClient):
    """The real client, with exactly one method replaced.

    `authorization_url` is inherited and therefore genuinely exercised - the
    scopes, `access_type=online`, the PKCE challenge and the state all come from
    production code. Only `exchange`, which is an HTTPS call to Google, is
    replaced.
    """

    exchange_result = _Exchange()

    async def exchange(self, *, code: str, code_verifier: str) -> str:
        self.exchange_result.calls.append({"code": code, "code_verifier": code_verifier})
        if self.exchange_result.error is not None:
            raise self.exchange_result.error
        assert self.exchange_result.id_token is not None, "the test did not mint a token"
        return self.exchange_result.id_token


class _FlowCommands:
    """Enough Redis for the flow store and the refresh-token store.

    `set(nx=...)` and the MULTI/EXEC `get`+`delete` are the single-use
    guarantees the flow store is built on, so they behave as Redis does rather
    than being waved through.
    """

    def __init__(self) -> None:
        self.values: dict[str, str] = {}
        self.counters: dict[str, int] = {}
        self.expiries: dict[str, int] = {}

    async def set(self, key, value, ex=None, nx=False):
        if nx and key in self.values:
            return None
        self.values[key] = value
        return True

    async def get(self, key):
        return self.values.get(key)

    async def delete(self, key):
        return 1 if self.values.pop(key, None) is not None else 0

    async def exists(self, key):
        return 1 if key in self.values else 0

    async def incr(self, key):
        self.counters[key] = self.counters.get(key, 0) + 1
        return self.counters[key]

    async def expire(self, key, seconds):
        self.expiries[key] = seconds
        return True

    async def rpush(self, key, value):
        return 1

    def pipeline(self, transaction=True):
        return _FlowPipeline(self)


class _FlowPipeline:
    def __init__(self, store: _FlowCommands) -> None:
        self._store = store
        self._queued: list[tuple[str, str]] = []

    async def __aenter__(self):
        return self

    async def __aexit__(self, *_: object):
        return False

    def get(self, key):
        self._queued.append(("get", key))

    def delete(self, key):
        self._queued.append(("delete", key))

    async def execute(self):
        results = []
        for operation, key in self._queued:
            if operation == "get":
                results.append(self._store.values.get(key))
            else:
                results.append(1 if self._store.values.pop(key, None) is not None else 0)
        return results


class _FlowRedis(FakeDependency):
    def __init__(self) -> None:
        super().__init__(name="redis")
        self.commands = _FlowCommands()  # type: ignore[assignment]


@pytest.fixture
def google_settings() -> Settings:
    return Settings(
        _env_file=None,
        environment="test",
        log_format="console",
        log_level="WARNING",
        cors_origins=[],
        rate_limit_enabled=False,
        google_enabled=True,
        google_client_id=CLIENT_ID,
        google_client_secret="a-test-client-secret",
        google_redirect_uri=REDIRECT_URI,
    )


@pytest.fixture
def exchange() -> Iterator[_Exchange]:
    holder = _Exchange()
    previous = _StubbedClient.exchange_result
    _StubbedClient.exchange_result = holder
    try:
        yield holder
    finally:
        _StubbedClient.exchange_result = previous


@pytest.fixture
def google_app(
    google_settings: Settings,
    db_session: AsyncSession,
    exchange: _Exchange,
    monkeypatch: pytest.MonkeyPatch,
) -> Iterator[FastAPI]:
    """The real application, with Google's network replaced and nothing else."""
    monkeypatch.setattr(google_routes, "GoogleOAuthClient", _StubbedClient)
    monkeypatch.setattr(google_routes, "_KEY_RING", _FixedKeyRing())

    application = create_app(google_settings)
    application.state.database = FakeDependency(name="postgresql")
    application.state.redis = _FlowRedis()

    async def _session(request: Request) -> AsyncIterator[AsyncSession]:
        # Parked exactly where the real dependency parks it, so `CommittingRoute`
        # finds it and really commits. The fixture binds with
        # `join_transaction_mode="create_savepoint"`, so that commit is a
        # savepoint release the outer rollback still undoes - which means these
        # tests observe the database as a client would, and still isolate.
        setattr(request.state, SESSION_STATE_ATTRIBUTE, db_session)
        yield db_session

    application.dependency_overrides[get_session] = _session
    application.dependency_overrides[get_entitlement_service] = AllowingEntitlements
    try:
        yield application
    finally:
        application.dependency_overrides.clear()


@pytest_asyncio.fixture
async def http(google_app: FastAPI) -> AsyncIterator[AsyncClient]:
    async with AsyncClient(
        transport=ASGITransport(app=google_app),
        base_url="http://wasla.test",
    ) as client:
        yield client


@pytest.fixture
def disabled_app(
    google_settings: Settings,
    db_session: AsyncSession,
    monkeypatch: pytest.MonkeyPatch,
) -> Iterator[FastAPI]:
    """The same application with Google switched off, for the 404 contract."""
    off = google_settings.model_copy(update={"google_enabled": False})
    application = create_app(off)
    application.state.database = FakeDependency(name="postgresql")
    application.state.redis = _FlowRedis()

    async def _session(request: Request) -> AsyncIterator[AsyncSession]:
        setattr(request.state, SESSION_STATE_ATTRIBUTE, db_session)
        yield db_session

    application.dependency_overrides[get_session] = _session
    application.dependency_overrides[get_entitlement_service] = AllowingEntitlements
    try:
        yield application
    finally:
        application.dependency_overrides.clear()


def _bearer(user: User, settings: Settings) -> dict[str, str]:
    token, _ = create_access_token(
        settings=settings,
        subject=user.id,
        tenant_id=None,
        token_version=user.token_version,
    )
    return {"Authorization": f"Bearer {token}"}


async def _account(
    session: AsyncSession,
    *,
    email: str,
    # Not a credential: nothing verifies it. `login` only ever asks whether the
    # column is None, which is what distinguishes a Google-only account.
    hashed_password: str | None = "not-a-real-hash",  # noqa: S107
    is_active: bool = True,
) -> User:
    user = User(
        email=email,
        full_name="Chosen In Wasla",
        hashed_password=hashed_password,
        is_active=is_active,
    )
    session.add(user)
    await session.flush()
    return user


async def _start(http: AsyncClient, path: str, **kwargs) -> tuple[str, str]:
    """Run a real `authorize` request and return its `state` and `nonce`.

    Read out of the authorization URL the application built, not invented here:
    a test that made up its own state would be testing nothing about the store
    that has to recognise it later.
    """
    response = await http.post(f"{API}{path}", **kwargs)
    assert response.status_code == 200, response.text
    query = parse_qs(urlsplit(response.json()["authorization_url"]).query)
    return query["state"][0], query["nonce"][0]


async def _identities(session: AsyncSession) -> list[FederatedIdentity]:
    return list((await session.scalars(select(FederatedIdentity))).all())


async def _audit(session: AsyncSession, action: AuditAction) -> list[AuditLog]:
    return list((await session.scalars(select(AuditLog).where(AuditLog.action == action))).all())


# --- POST /auth/google/authorize -----------------------------------------


async def test_authorize_is_open_and_returns_a_real_google_url(http: AsyncClient) -> None:
    """Unauthenticated by design: this is how somebody with no account starts."""
    response = await http.post(f"{API}/auth/google/authorize")

    assert response.status_code == 200
    body = response.json()
    assert set(body) == {"authorization_url", "expires_in"}
    assert body["expires_in"] > 0

    parts = urlsplit(body["authorization_url"])
    assert parts.scheme == "https"
    assert parts.netloc == "accounts.google.com"
    query = parse_qs(parts.query)
    assert query["client_id"] == [CLIENT_ID]
    assert query["redirect_uri"] == [REDIRECT_URI]
    assert query["response_type"] == ["code"]
    assert query["code_challenge_method"] == ["S256"]
    # The parameter that makes "no refresh token is ever stored" structural
    # rather than a rule somebody has to remember.
    assert query["access_type"] == ["online"]
    assert query["scope"] == ["openid email profile"]


async def test_two_authorizations_never_share_a_state_or_a_nonce(http: AsyncClient) -> None:
    first_state, first_nonce = await _start(http, "/auth/google/authorize")
    second_state, second_nonce = await _start(http, "/auth/google/authorize")

    assert first_state != second_state
    assert first_nonce != second_nonce


async def test_authorize_is_404_when_google_is_not_configured(disabled_app: FastAPI) -> None:
    """A feature nobody enabled does not exist here, which is not a 503."""
    async with AsyncClient(
        transport=ASGITransport(app=disabled_app), base_url="http://wasla.test"
    ) as client:
        response = await client.post(f"{API}/auth/google/authorize")

    assert response.status_code == 404


# --- POST /auth/google/callback ------------------------------------------


async def test_a_first_login_opens_a_session_and_creates_one_account(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """The whole flow over HTTP: authorize, exchange, verify, enrol, sign in."""
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)

    response = await http.post(
        f"{API}/auth/google/callback",
        json={"code": "an-authorization-code", "state": state},
    )

    assert response.status_code == 200, response.text
    body = response.json()
    # The same shape `/auth/login` answers, which is the point: nothing
    # downstream can tell which method opened the session.
    assert {"access_token", "refresh_token", "token_type"} <= set(body)
    assert body["token_type"] == "bearer"

    # The PKCE verifier really travelled to the exchange.
    assert exchange.calls and exchange.calls[0]["code"] == "an-authorization-code"
    assert exchange.calls[0]["code_verifier"]

    user = await db_session.scalar(select(User).where(User.email == GOOGLE_EMAIL))
    assert user is not None
    assert user.full_name == GOOGLE_NAME
    assert user.avatar_url == GOOGLE_PICTURE
    assert user.hashed_password is None
    assert user.email_verified_at is not None

    identities = await _identities(db_session)
    assert len(identities) == 1
    assert identities[0].provider is IdentityProvider.GOOGLE
    assert identities[0].provider_subject == SUBJECT
    assert identities[0].user_id == user.id


async def test_the_session_from_a_google_login_authenticates_auth_me(
    http: AsyncClient,
    exchange: _Exchange,
) -> None:
    """The end the browser flow would reach: a usable session, and the profile.

    This is the assertion the real browser test would make, minus the browser.
    """
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)
    session = (
        await http.post(
            f"{API}/auth/google/callback",
            json={"code": "c", "state": state},
        )
    ).json()

    me = await http.get(
        f"{API}/auth/me",
        headers={"Authorization": f"Bearer {session['access_token']}"},
    )

    assert me.status_code == 200
    profile = me.json()
    assert profile["email"] == GOOGLE_EMAIL
    assert profile["full_name"] == GOOGLE_NAME
    assert profile["avatar_url"] == GOOGLE_PICTURE
    assert profile["email_verified_at"] is not None
    # Google supplies no workspace name or slug, so such an account has none
    # until it is invited somewhere.
    assert profile["workspaces"] == []


async def test_a_second_login_refreshes_the_profile_but_not_the_address(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """Profile refresh over HTTP, including the address that must not move.

    The security half and the feature half in one test on purpose: the name and
    picture moving is what makes the address standing still a decision rather
    than the refresh silently not running.
    """
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)
    await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    moved_picture = "https://lh3.googleusercontent.com/a/second=s96-c"
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(
        nonce=nonce,
        name="A Renamed Person",
        picture=moved_picture,
        email="somebody-elses@example.com",
    )
    second = await http.post(f"{API}/auth/google/callback", json={"code": "c2", "state": state})

    assert second.status_code == 200
    db_session.expire_all()

    user = await db_session.scalar(select(User).where(User.email == GOOGLE_EMAIL))
    assert user is not None
    assert user.full_name == "A Renamed Person"
    assert user.avatar_url == moved_picture
    assert user.email == GOOGLE_EMAIL

    # No account was created on the address the second token claimed, and no
    # second identity for the same subject.
    assert (
        await db_session.scalar(select(User).where(User.email == "somebody-elses@example.com"))
        is None
    )
    assert len(await _identities(db_session)) == 1


async def test_a_verified_google_address_never_claims_an_existing_account(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """Collision refusal (ADR-049), over HTTP.

    Proving control of a mailbox is not proof of anything about an account
    registered under it. The refusal must be a 409 that signs nobody in, links
    nothing, and leaves the existing account's password untouched.
    """
    existing = await _account(db_session, email=GOOGLE_EMAIL, hashed_password="the-real-hash")
    # Read before the expire below: dereferencing an expired attribute on an
    # async session is a lazy load, which is an error rather than a query.
    existing_id = existing.id

    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)
    response = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert response.status_code == 409
    body = response.json()
    assert "access_token" not in json.dumps(body)

    db_session.expire_all()
    reloaded = await db_session.get(User, existing_id)
    assert reloaded is not None
    assert reloaded.hashed_password == "the-real-hash"
    assert reloaded.avatar_url is None
    assert await _identities(db_session) == []
    assert await _audit(db_session, AuditAction.GOOGLE_LOGIN_FAILED)


async def test_a_disabled_account_is_refused_with_403(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """A disabled account keeps its identity but may not open a session."""
    user = await _account(db_session, email=GOOGLE_EMAIL, hashed_password=None, is_active=False)
    db_session.add(
        FederatedIdentity(
            user_id=user.id,
            provider=IdentityProvider.GOOGLE,
            provider_subject=SUBJECT,
        )
    )
    await db_session.flush()

    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)
    response = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert response.status_code == 403
    assert "access_token" not in json.dumps(response.json())
    assert await _audit(db_session, AuditAction.GOOGLE_LOGIN_FAILED)


async def test_a_replayed_state_is_refused(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """Single use is the replay control, and it is enforced in the store."""
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)

    first = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})
    assert first.status_code == 200

    replay = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert replay.status_code == 401
    # The replay did not enrol a second account behind the first.
    assert len((await db_session.scalars(select(User))).all()) == 1


async def test_an_unknown_state_is_refused_without_reaching_google(
    http: AsyncClient,
    exchange: _Exchange,
) -> None:
    """The state is spent first, so a stranger cannot make us call Google."""
    response = await http.post(
        f"{API}/auth/google/callback",
        json={"code": "c", "state": "a" * 43},
    )

    assert response.status_code == 401
    assert exchange.calls == []


async def test_a_token_with_the_wrong_nonce_is_refused(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """The nonce binds the token to the authorization this process started."""
    state, _ = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce="a-nonce-from-somewhere-else")

    response = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert response.status_code == 401
    assert (await db_session.scalars(select(User))).all() == []


async def test_a_token_signed_by_another_key_is_refused(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """The signature check, exercised through the route rather than in isolation."""
    state, nonce = await _start(http, "/auth/google/authorize")
    forged_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    now = datetime.now(UTC)
    exchange.id_token = jwt.encode(
        {
            "iss": ISSUER,
            "aud": CLIENT_ID,
            "sub": SUBJECT,
            "email": GOOGLE_EMAIL,
            "email_verified": True,
            "nonce": nonce,
            "iat": int(now.timestamp()),
            "exp": int((now + timedelta(minutes=5)).timestamp()),
        },
        forged_key,
        algorithm="RS256",
        headers={"kid": KID},
    )

    response = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert response.status_code == 401
    assert (await db_session.scalars(select(User))).all() == []


async def test_an_unverified_google_address_is_refused(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce, email_verified=False)

    response = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert response.status_code == 401
    assert (await db_session.scalars(select(User))).all() == []


async def test_a_hostile_picture_url_does_not_reach_the_database(
    http: AsyncClient,
    exchange: _Exchange,
    db_session: AsyncSession,
) -> None:
    """A signature is not a safety guarantee, asserted at the storage boundary.

    Google signs what the account says, so this token is perfectly valid and
    still carries a payload. The login must succeed and the column must be null.
    """
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce, picture="javascript:alert(document.cookie)")

    response = await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})

    assert response.status_code == 200
    user = await db_session.scalar(select(User).where(User.email == GOOGLE_EMAIL))
    assert user is not None
    assert user.avatar_url is None


async def test_the_callback_validates_its_body(http: AsyncClient) -> None:
    response = await http.post(f"{API}/auth/google/callback", json={"code": "only-a-code"})

    assert response.status_code == 422


async def test_callback_is_404_when_google_is_not_configured(disabled_app: FastAPI) -> None:
    async with AsyncClient(
        transport=ASGITransport(app=disabled_app), base_url="http://wasla.test"
    ) as client:
        response = await client.post(
            f"{API}/auth/google/callback",
            json={"code": "c", "state": "a" * 43},
        )

    assert response.status_code == 404


# --- POST /auth/identities/google/authorize -------------------------------


async def test_starting_a_link_requires_authentication(http: AsyncClient) -> None:
    response = await http.post(f"{API}/auth/identities/google/authorize")

    assert response.status_code == 401


async def test_starting_a_link_returns_a_url_for_the_signed_in_account(
    http: AsyncClient,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    user = await _account(db_session, email="member@example.com")

    response = await http.post(
        f"{API}/auth/identities/google/authorize",
        headers=_bearer(user, google_settings),
    )

    assert response.status_code == 200
    assert set(response.json()) == {"authorization_url", "expires_in"}


# --- POST /auth/identities/google/link ------------------------------------


async def test_linking_requires_authentication(http: AsyncClient) -> None:
    response = await http.post(
        f"{API}/auth/identities/google/link",
        json={"code": "c", "state": "a" * 43},
    )

    assert response.status_code == 401


async def test_linking_attaches_google_and_fills_an_empty_profile(
    http: AsyncClient,
    exchange: _Exchange,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    user = await _account(db_session, email="member@example.com")
    user_id = user.id
    headers = _bearer(user, google_settings)
    state, nonce = await _start(http, "/auth/identities/google/authorize", headers=headers)
    exchange.id_token = _id_token(nonce=nonce)

    response = await http.post(
        f"{API}/auth/identities/google/link",
        json={"code": "c", "state": state},
        headers=headers,
    )

    assert response.status_code == 200
    body = response.json()
    assert body["provider"] == "google"
    assert body["connected_at"]
    # Connecting is not signing in, so it has never been used to open a session.
    assert body["last_login_at"] is None
    # And it is emphatically not a session.
    assert "access_token" not in json.dumps(body)

    db_session.expire_all()
    reloaded = await db_session.get(User, user_id)
    assert reloaded is not None
    assert reloaded.avatar_url == GOOGLE_PICTURE
    assert reloaded.full_name == GOOGLE_NAME
    # Linking must not cost the account its password.
    assert reloaded.hashed_password == "not-a-real-hash"

    identities = await _identities(db_session)
    assert len(identities) == 1
    assert identities[0].user_id == user_id
    assert await _audit(db_session, AuditAction.GOOGLE_IDENTITY_LINKED)


async def test_a_login_flow_cannot_be_finished_at_the_link_endpoint(
    http: AsyncClient,
    exchange: _Exchange,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    """Flows carry their kind, so the weaker entry cannot feed the stronger one."""
    user = await _account(db_session, email="member@example.com")
    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)

    response = await http.post(
        f"{API}/auth/identities/google/link",
        json={"code": "c", "state": state},
        headers=_bearer(user, google_settings),
    )

    assert response.status_code == 401
    assert await _identities(db_session) == []


async def test_a_link_flow_started_by_somebody_else_is_refused(
    http: AsyncClient,
    exchange: _Exchange,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    """The binding is the account recorded when the flow began, not the token."""
    starter = await _account(db_session, email="starter@example.com")
    finisher = await _account(db_session, email="finisher@example.com")

    state, nonce = await _start(
        http,
        "/auth/identities/google/authorize",
        headers=_bearer(starter, google_settings),
    )
    exchange.id_token = _id_token(nonce=nonce)

    response = await http.post(
        f"{API}/auth/identities/google/link",
        json={"code": "c", "state": state},
        headers=_bearer(finisher, google_settings),
    )

    assert response.status_code == 401
    assert await _identities(db_session) == []


async def test_a_google_account_already_connected_elsewhere_is_refused(
    http: AsyncClient,
    exchange: _Exchange,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    """Moving an identity would walk somebody's sign-in method off their account."""
    owner = await _account(db_session, email="owner@example.com")
    db_session.add(
        FederatedIdentity(
            user_id=owner.id,
            provider=IdentityProvider.GOOGLE,
            provider_subject=SUBJECT,
        )
    )
    other = await _account(db_session, email="other@example.com")
    await db_session.flush()

    headers = _bearer(other, google_settings)
    state, nonce = await _start(http, "/auth/identities/google/authorize", headers=headers)
    exchange.id_token = _id_token(nonce=nonce)

    response = await http.post(
        f"{API}/auth/identities/google/link",
        json={"code": "c", "state": state},
        headers=headers,
    )

    assert response.status_code == 409
    identities = await _identities(db_session)
    assert len(identities) == 1
    assert identities[0].user_id == owner.id
    assert await _audit(db_session, AuditAction.GOOGLE_IDENTITY_LINK_FAILED)


# --- DELETE /auth/identities/google ---------------------------------------


async def test_unlinking_requires_authentication(http: AsyncClient) -> None:
    response = await http.delete(f"{API}/auth/identities/google")

    assert response.status_code == 401


async def test_unlinking_removes_the_identity_from_an_account_with_a_password(
    http: AsyncClient,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    user = await _account(db_session, email="member@example.com")
    db_session.add(
        FederatedIdentity(
            user_id=user.id,
            provider=IdentityProvider.GOOGLE,
            provider_subject=SUBJECT,
        )
    )
    await db_session.flush()

    response = await http.delete(
        f"{API}/auth/identities/google",
        headers=_bearer(user, google_settings),
    )

    assert response.status_code == 204
    assert not response.content
    assert await _identities(db_session) == []
    assert await _audit(db_session, AuditAction.GOOGLE_IDENTITY_UNLINKED)


async def test_unlinking_the_last_way_in_is_refused(
    http: AsyncClient,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    """A Google-only account has no password, so removing Google locks it out."""
    user = await _account(db_session, email=GOOGLE_EMAIL, hashed_password=None)
    db_session.add(
        FederatedIdentity(
            user_id=user.id,
            provider=IdentityProvider.GOOGLE,
            provider_subject=SUBJECT,
        )
    )
    await db_session.flush()

    response = await http.delete(
        f"{API}/auth/identities/google",
        headers=_bearer(user, google_settings),
    )

    assert response.status_code == 403
    assert len(await _identities(db_session)) == 1


async def test_unlinking_when_nothing_is_connected_is_404(
    http: AsyncClient,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    user = await _account(db_session, email="member@example.com")

    response = await http.delete(
        f"{API}/auth/identities/google",
        headers=_bearer(user, google_settings),
    )

    assert response.status_code == 404


# --- Cross-cutting --------------------------------------------------------


async def test_no_response_ever_carries_google_material(
    http: AsyncClient,
    exchange: _Exchange,
    google_settings: Settings,
    db_session: AsyncSession,
) -> None:
    """The client secret, the code and the ID token stay on this side.

    Checked across every route in one place, because "no route leaks it" is the
    property, and asserting it per route invites the next route to be the one
    nobody checked.
    """
    user = await _account(db_session, email="member@example.com")
    headers = _bearer(user, google_settings)

    state, nonce = await _start(http, "/auth/google/authorize")
    exchange.id_token = _id_token(nonce=nonce)
    bodies = [
        (await http.post(f"{API}/auth/google/authorize")).text,
        (await http.post(f"{API}/auth/google/callback", json={"code": "c", "state": state})).text,
        (await http.post(f"{API}/auth/identities/google/authorize", headers=headers)).text,
        (
            await http.post(
                f"{API}/auth/identities/google/link",
                json={"code": "c", "state": "b" * 43},
                headers=headers,
            )
        ).text,
        (await http.delete(f"{API}/auth/identities/google", headers=headers)).text,
    ]

    secret = google_settings.google_client_secret
    assert secret is not None
    for body in bodies:
        assert secret not in body
        assert exchange.id_token not in body
        # The nonce and the PKCE verifier are server-side state; the authorize
        # responses carry a nonce inside the Google URL by design, so only the
        # verifier is checked here.
        for call in exchange.calls:
            assert call["code_verifier"] not in body


async def test_the_stored_flow_is_opaque(http: AsyncClient, google_app: FastAPI) -> None:
    """What is written to Redis names no account and no address."""
    state, _ = await _start(http, "/auth/google/authorize")

    stored = google_app.state.redis.client.values
    assert stored, "the flow was not written"
    for key, payload in stored.items():
        assert state in key
        decoded = json.dumps(json.loads(payload)) if payload.startswith("{") else payload
        assert GOOGLE_EMAIL not in decoded
        assert base64.b64encode(GOOGLE_EMAIL.encode()).decode() not in decoded
